In [1]:
import pandas as pd

In [2]:
# load the school demo data from the open api server
demo_url = "https://data.cityofnewyork.us/resource/45j8-f6um.csv?$limit=10000000"
df = pd.read_csv(demo_url)

In [3]:
# parse the dbn into district, boro, and boro_name
boros = {"M":"Manhattan", "K": "Brooklyn", "X":"Bronx", "R":"Staten Island", "Q":"Queens"}
df["district"] = df.dbn.apply(lambda dbn: int(dbn[:2]))
df["boro"] = df.dbn.apply(lambda dbn: dbn[2])
df["boro_name"] = df.boro.apply(lambda x: boros[x])

# df = df.sort_values(by="dbn", ascending=False)

# df.boro.drop_duplicates()

# df[["dbn", "district", "boro"]]

In [9]:
# calculate boro and district averages for each demo group


# first get the sums
demo_agg = {
  'total_enrollment': "sum",
  'black': "sum",
  'white': "sum",
  'asian': "sum",
  'hispanic': "sum",
  'multiple_race_categories': "sum",
  'students_with_disabilities': "sum",
  'english_language_learners': "sum",
  'poverty': "sum"
}

districts = df.groupby(["district", "year"]).agg(demo_agg).reset_index()

# add a new col that combines blackand hispanic
# this might not be right, if we are double counting students who are black and hispanic
districts["black_hispanic"] = districts.black + districts.hispanic

for demo in demo_agg:
    districts[demo + "_pct"] = districts[demo] / districts.total_enrollment
districts["black_hispanic_pct"] = districts["black_hispanic"] / districts.total_enrollment


districts.sort_values(by="black_pct", ascending=False)

,district,year,total_enrollment,black,white,asian,hispanic,multiple_race_categories,students_with_disabilities,english_language_learners,...,total_enrollment_pct,black_pct,white_pct,asian_pct,hispanic_pct,multiple_race_categories_pct,students_with_disabilities_pct,english_language_learners_pct,poverty_pct,black_hispanic_pct
85,18,2014-15,16114,14318,274,203,1123,196,2777,779,...,1.0,0.888544,0.017004,0.012598,0.069691,0.012163,0.172335,0.048343,0.785714,0.958235
86,18,2015-16,15545,13727,281,196,1117,224,2811,724,...,1.0,0.883049,0.018077,0.012609,0.071856,0.014410,0.180830,0.046574,0.768672,0.954905
87,18,2016-17,15129,13242,356,210,1093,228,2797,930,...,1.0,0.875273,0.023531,0.013881,0.072245,0.015070,0.184877,0.061471,0.773415,0.947518
88,18,2017-18,14566,12551,421,246,1130,218,2896,1070,...,1.0,0.861664,0.028903,0.016889,0.077578,0.014966,0.198819,0.073459,0.798503,0.939242
89,18,2018-19,14069,11967,462,269,1130,241,2764,1096,...,1.0,0.850594,0.032838,0.019120,0.080318,0.017130,0.196460,0.077902,0.772265,0.930912
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
116,24,2015-16,57749,1651,8137,11174,36222,565,9360,12694,...,1.0,0.028589,0.140903,0.193493,0.627232,0.009784,0.162081,0.219813,0.713848,0.655821
117,24,2016-17,58143,1551,8128,11430,36399,635,9696,13557,...,1.0,0.026676,0.139793,0.196584,0.626025,0.010921,0.166761,0.233167,0.702699,0.652701
99,20,2018-19,51001,1348,12764,22437,13851,601,7885,11864,...,1.0,0.026431,0.250270,0.439933,0.271583,0.011784,0.154605,0.232623,0.763711,0.298014
118,24,2017-18,57729,1500,7905,11459,36106,759,9933,13048,...,1.0,0.025983,0.136933,0.198496,0.625440,0.013148,0.172063,0.226022,0.791145,0.651423
119,24,2018-19,57047,1462,7558,11306,35901,820,9780,12737,...,1.0,0.025628,0.132487,0.198187,0.629323,0.014374,0.171438,0.223272,0.754413,0.654951

In [10]:
d13 = districts.query("district==13")
d13 = d13.query("year=='2018-19'")
# d13[["dbn", "school_name", "total_enrollment", "asian", "black", "hispanic", "white"]]
d13.transpose()

                                      64
district                              13
year                             2018-19
total_enrollment                   21022
black                               8781
white                               3560
asian                               4421
hispanic                            3533
multiple_race_categories             727
students_with_disabilities          2983
english_language_learners            882
poverty                            13472
black_hispanic                     12314
total_enrollment_pct                 1.0
black_pct                       0.417705
white_pct                       0.169346
asian_pct                       0.210303
hispanic_pct                    0.168062
multiple_race_categories_pct    0.034583
students_with_disabilities_pct  0.141899
english_language_learners_pct   0.041956
poverty_pct                     0.640852
black_hispanic_pct              0.585767

In [11]:
districts["district"].unique()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 75, 79,
       84])