In [58]:
# import pandas and our schools.py functions
import pandas as pd
import schools

# load the schools demographic data using schools.py
df = schools.load_demographics()
print("loaded data")

loaded data

In [55]:
# make a new df with only the most current year
# we will put the 5 year changes into this data frame

# call unique() on year to see what all of the years are
print("all years:", df.year.unique())

# call copy on the query so that it actually copies the values, not just a view
# of the original dataframe
latest = df.query("year == 2019").copy()

all years: [2015 2016 2017 2018 2019]

In [56]:
# now subtract the 2015 data from the data in latest to calc changes
# write a function to do this, and then "apply" it to each row in `latest`


# this is a generic function that returns the change in a row
# compared to the 
def calc_pov_change(row):
    dbn = row["dbn"]
    # start is the row for the same school, but for the start year
    start = df.query(f"dbn == '{dbn}' and year == 2015")

    # it's possible there might not be 2015 data for every school
    # for now, make it look like no change, 
    # another approach would be to look for 2016, 17, 18 until we find a year
    if len(start) != 1:
        return 0

    current_pov = float(row["poverty_1"])
    previous_pov = float(start["poverty_1"])
    
    return current_pov - previous_pov

# `axis=1` means apply to each row in the dataframe
latest["poverty_change"] = latest.apply(calc_pov_change, axis=1)

In [57]:
latest.sort_values(by=["poverty_change"], inplace=True)

# these are the 20 schools that lost the most wealth
latest[["dbn", "boro", "school_name", "poverty_change"]].head(20)

,dbn,boro,school_name,poverty_change
6371,27Q336,Q,Curious Young Learners Pre-K Center,-0.485
3864,15K767,K,The Little Brooklyn Pre-K Center,-0.406
3779,15K442,K,M.S. 442 Carroll Gardens School for Innovation,-0.399
7106,30Q389,Q,District 30 Pre-K Center,-0.373
7428,31R066,R,The Richmond Pre-K Center,-0.356
3283,13K056,K,P.S. 056 Lewis H. Latimer,-0.297
1635,07X533,X,Learning through Play Pre-K Center,-0.283
3353,13K313,K,Dock Street School for STEAM Studies,-0.278
5267,22K853,K,The Joan Snow Pre-K Center,-0.273
3328,13K282,K,P.S. 282 Park Slope,-0.249
3814,15K497,K,The Boerum Hill School for International Studies,-0.240
507,02M414,M,N.Y.C. Museum School,-0.240
4862,20K768,K,District 20 Pre-K Center,-0.224
8679,84Q339,Q,Success Academy Charter School - Springfield G...,-0.222
6886,29Q381,Q,District 29 Pre-K Center,-0.222
5072,21K840,K,Brooklyn's Daily Discovery Pre-K Center,-0.220
3879,15K863,K,Pre-K Center at Bishop Ford School Site,-0.217
5609,24Q296,Q,Pan American International High School,-0.216
8216,84K741,K,Success Academy Crown Heights (Brooklyn 7),-0.188
3564,14K414,K,Brooklyn Arbor Elementary School,-0.186

In [50]:
latest.sort_values(by=["poverty_change"], inplace=True, ascending=False)

# these are the 20 schools that gained the most wealth
latest[["dbn", "boro", "school_name", "poverty_change"]].head(20)

,dbn,boro,school_name,poverty_change
119,01M515,M,Lower East Side Preparatory High School,0.397
7716,75K721,K,P.S. K721 - Brooklyn Occupational Training Center,0.393
7928,75X721,X,P.S. X721 - Stephen McSweeney School,0.364
8733,84Q705,Q,Renaissance Charter School,0.359
8728,84Q704,Q,Merrick Academy - Queens Public Charter School,0.356
663,02M550,M,Liberty High School Academy for Newcomers,0.347
7841,75Q721,Q,John F. Kennedy Jr. School,0.345
7951,79M645,M,School for Cooperative Technical Education,0.340
7741,75M079,M,P.S. M079 - Horan School,0.335
8211,84K740,K,Brooklyn Scholars Charter School,0.334
7821,75Q233,Q,P.S. Q233,0.331
8832,84X347,X,International Leadership Charter High School,0.322
7943,75X811,X,P.S. X811,0.320
7776,75M721,M,P.S. M721 - Manhattan Occupational Training Ce...,0.315
7706,75K373,K,P.S. 373 - Brooklyn Transition Center,0.310
7966,79Q950,Q,Pathways to Graduation,0.307
3383,13K439,K,Brooklyn International High School,0.303
1095,04M964,M,Central Park East II,0.300
8433,84M186,M,Harlem Hebrew Language Charter School,0.299
7826,75Q255,Q,P.S. Q255,0.295